apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.yaml
  - solvers
  - issuers/issuers.yaml

generatorOptions:
  disableNameSuffixHash: true

# Neede if you have an internal authoritive zone with the same name as external one
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --dns01-recursive-nameservers-only
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
    target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
  - target:
      kind: CustomResourceDefinition
    patch: |- 
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1instance
