apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.webhook.abion.com
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/cert-manager-webhook-abion-webhook-tls"
spec:
  group: acme.webhook.abion.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-abion
    namespace: cert-manager
  version: v1alpha1