apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-abion-ca
  namespace: cert-manager
spec:
  secretName: cert-manager-webhook-abion-ca
  duration: 43800h # 5y
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  commonName: ca.cert-manager-webhook-abion.cert-manager
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-abion-webhook-tls
  namespace: cert-manager
spec:
  secretName: cert-manager-webhook-abion-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: cert-manager-webhook-abion-ca
  dnsNames:
  - cert-manager-webhook-abion
  - cert-manager-webhook-abion.cert-manager
  - cert-manager-webhook-abion.cert-manager.svc
